### ISSUE TITLE
GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable Can't create GLFW window

### ISSUE THREAD

**Issue by ChrisEddy** [webmixedreality/exokit#126]
## Summary
GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable.
Can't create GLFW window.

## My System:
Ubuntu 18.04 LTS
VirtualBox
Fully updated OS
Node v10.4.1

## Scenario
node install went good, 0 problems.
When using `./exokit.sh -h ` 

### Error
`
chris@chris-VirtualBox:~/exokit$ ./exokit.sh -h
THREE.WebGLRenderer 93
GLX: Forward compatibility requested but GLX_ARB_create_context_profile is unavailable
Can't create GLFW window
TypeError: gl.getExtension is not a function
    at Object.get (js/three.js:14966:22)
    at initGLContext (js/three.js:21877:15)
    at new WebGLRenderer (js/three.js:21924:3)
    at file:///home/chris/exokit/node_modules/exokit-home/index.html:375:22
    at file:///home/chris/exokit/node_modules/exokit-home/index.html:3061:3
    at _runJavascript (/home/chris/exokit/core.js:3489:15)
    at HTMLScriptElement.on.innerHTML (/home/chris/exokit/core.js:2709:9)
    at HTMLScriptElement.emit (events.js:182:13)
    at HTMLScriptElement.EventEmitter.emit (domain.js:442:20)
    at HTMLScriptElement._emit (/home/chris/exokit/core.js:195:40)
ReferenceError: renderer is not defined
    at fakeDisplay.requestPresent.then (file:///home/chris/exokit/node_modules/exokit-home/index.html:174:11)
`

**Comment by modulesio** [comment]
Thanks, this looks like a 3D acellerator support problem.

Is the 3D acceleration feature of virtual box enabled for this vm? Could you screenshot that tab?

**Comment by ChrisEddy** [comment]
3d acceleration was turned on, but 2d acceleration was turned off in Vbox.

**Comment by modulesio** [comment]
Closing as a VirtualBox issue. VirtualBox is not a current support target.
