### ISSUE TITLE
Add Oculus support

### ISSUE THREAD

**Issue by dmarcos** [webmixedreality/exokit#146]
I also tried Oculus over Steam VR. Running `exokit.sh -h` and pressing ctrl-1 to enter VR mode results in a crash.

**Comment by dmarcos** [comment]
This is the error I get when launching `node index.js -h` after pressing `ctrol-1` and Oculus present via SteamVR:

```
Error: Compositor error: VRCompositorError_TextureUsesUnsupportedFormat
    at _blit (C:\exokit\index.js:701:39)
    at Timeout._recurse [as _onTimeout] (C:\exokit\index.js:1151:5)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Bugsnag:  Encountered an uncaught error, terminating…
Error: Compositor error: VRCompositorError_TextureUsesUnsupportedFormat
    at _blit (C:\exokit\index.js:701:39)
    at Timeout._recurse [as _onTimeout] (C:\exokit\index.js:1151:5)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

**Comment by modulesio** [comment]
Thanks, this looks like the format of the texture is one oculus binding doesn't like. Needs some research.

**Comment by modulesio** [comment]
Would be curious if the [OpenVR example](https://github.com/ValveSoftware/openvr/blob/60eb187801956ad277f1cae6680e3a410ee0873b/samples/hellovr_opengl/hellovr_opengl_main.cpp#L1397) works in Oculus SteamVR, because that's pretty much [what Exokit is doing](https://github.com/webmixedreality/exokit/blob/f5083fa3b783dce0878a38ad787f1103b6d518f2/deps/exokit-bindings/glfw/src/glfw.cc#L870).

**Comment by modulesio** [comment]
Work on this issue might have conflicts with https://github.com/webmixedreality/exokit/pull/286.

**Comment by dmarcos** [comment]
Thanks for letting me know. I'm planning to get back to this after next week.

**Comment by modulesio** [comment]
@dmarcos Is there a starting base here? I think @cmdrflexo wanted to dive in.

**Comment by ngokevin** [comment]
Not sure if he had too much, at least not NAN bindings. I think flexo could start. I was gonna start on the mobile SDK.

**Comment by shaneharris** [comment]
Just to throw in my two cents here, I have been able to use it on oculus through steam many times. 

I usually start like this in the exokit folder:

Exokit version 0.0.482 - installed via git clone and npm install.

`node . https://aframe.io/a-painter/`

**Comment by modulesio** [comment]
Is there any performance hit or gotchas when doing so? I'm glad it works either way, was a pleasant surprise to hear.

**Comment by shaneharris** [comment]
Not that i'm aware of, it just works. I actually used it quite a while ago around version 0.0.420 :smirk: and it worked just as well. Only issue i have was the movement-controls component had its axis' reversed but i don't think that was anything to do with exokit as it was already reported on their issue tracker. 

Maybe we should all list the kit we have in a sticky location so we know what everyone has to test with.

**Comment by ngokevin** [comment]
Cool! Still will want native support, especially as headsets go standalone. I think there'd be some perf issues (we saw on WMR + Steam), perhaps as the app scales. Like does ATW work?

**Comment by modulesio** [comment]
Agree, should aim for native on all desired platforms. I'm guessing there's no other option for Santa Cruz/Quest anyway.

Quest is Android though, so I'm not sure how much the binding would be Android vs how much OVR.

**Comment by shaneharris** [comment]
I'm not sure on the ATW, how do i check that?

**Comment by ZNixian** [comment]
Hi, I'm planning to start work on adding a native LibOVR binding. Just checking if anyone else has started work on this?

**Comment by modulesio** [comment]
Would be much appreciated!

I don't think @dmarcos got very far, though there is a binary module at https://www.npmjs.com/package/native-oculus-deps

**Comment by modulesio** [comment]
@dmarcos related to this, would you mind sharing collaborator status on `npm`/`native-oculus-deps` with [`@kazmer`](https://www.npmjs.com/~kazmer)?

**Comment by dmarcos** [comment]
Done

**Comment by modulesio** [comment]
Thanks!
