### ISSUE TITLE
Resource loading timeouts

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#298]
Timeouts are inevitable, but here's one that doesn't get caught and therefore brings down the process. I haven't been able to repro; this is courtesy of @shaneharris.

```
A-Frame Version: 0.7.0 (Date 2018-02-05, Commit #39daf67)
three Version: github:dmarcos/three.js#r89fix
WebVR Polyfill Version: ^0.9.40
core:schema:warn Default value `0 1 0` does not match type `vec3` in component `teleport-controls` 
THREE.WebGLRenderer 89
A-PAINTER Version: 1.2
core:a-assets:warn Cross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)  https://cdn.aframe.io/a-painter/sounds/ui_click0.ogg
core:a-assets:warn Cross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)  https://cdn.aframe.io/a-painter/sounds/ui_click1.ogg
core:a-assets:warn Cross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)  https://cdn.aframe.io/a-painter/sounds/ui_menu.ogg
core:a-assets:warn Cross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)  https://cdn.aframe.io/a-painter/sounds/ui_undo.ogg
core:a-assets:warn Cross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)  https://cdn.aframe.io/a-painter/sounds/ui_tick.ogg
core:a-assets:warn Cross-origin element (e.g., <img>) was requested without `crossorigin` set. A-Frame will re-request the asset with `crossorigin` attribute set. Please set `crossorigin` on the element (e.g., <img crossorigin="anonymous">)  https://cdn.aframe.io/a-painter/sounds/ui_paint.ogg
core:schema:warn Unknown property `button` for component/system `teleport-controls`. 
core:schema:warn Unknown property `ground` for component/system `teleport-controls`. 
core:schema:warn Unknown property `button` for component/system `teleport-controls`. 
core:schema:warn Unknown property `ground` for component/system `teleport-controls`. 
THREE.WebGLRenderer: image is not power of two (3584x2944). Resized to 2048x2048 <img src="assets/images/brush_atlas.png"/>
OBJLoader: 18.011ms
OBJLoader: 1.882ms
OBJLoader: 24.747ms
OBJLoader: 14.948ms
OBJLoader: 3.132ms
{ Error: connect ETIMEDOUT 104.25.104.6:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: [32m'ETIMEDOUT'[39m,
  code: [32m'ETIMEDOUT'[39m,
  syscall: [32m'connect'[39m,
  address: [32m'104.25.104.6'[39m,
  port: [33m443[39m }
```

**Comment by shaneharris** [comment]
im seeing more of these. They seem to be intermittent and when you get one it seems to cascade fail onto other connections after that. 

Is there a global way to catch these network errors?


```C:\workspace\expanse-app\exokit>node . -x none -s 800x600 http://localhost:8080/
A-Frame Version: 0.8.2 (Date 2018-04-15, Commit #b20527f)
three Version: github:supermedium/three.js#r90fixMTLLoader
WebVR Polyfill Version: ^0.10.5
aframe-material-collection version 0.4.31
THREE.WebGLRenderer 90
extras:primitives:warn Mapping keys should be specified in lower case. The mapping key amplitudeVariance may not be recognized
extras:primitives:warn Mapping keys should be specified in lower case. The mapping key speedVariance may not be recognized
core:a-assets:warn Asset loading timed out in   3000 ms
THREE.MeshPhongMaterial: .shading has been removed. Use the boolean .flatShading instead.
Shane's Editor Version 2.0.7
Connected to Expanse API
Templates loaded in: 0.19s
Scene Downloaded.
Loading Scene...
GLTFLoader: 25.441ms
(node:16360) Warning: No such label 'GLTFLoader' for console.timeEnd()
Scene loaded in: 4.036s
failed to load image: https://i.imgur.com/rkZJOdn.png
ErrorEvent {
  type: 'error',
  target: <img src="https://i.imgur.com/rkZJOdn.png"/>,
  bubbles: false,
  cancelable: false,
  defaultPrevented: false,
  propagationStopped: false,
  currentTarget: <img src="https://i.imgur.com/rkZJOdn.png"/>,
  message:
   'request to https://i.imgur.com/rkZJOdn.png failed, reason: connect ETIMEDOUT 151.101.16.193:443',
  stack:
   'FetchError: request to https://i.imgur.com/rkZJOdn.png failed, reason: connect ETIMEDOUT 151.101.16.193:443\n    at ClientRequest.<anonymous> (C:\\workspace\\expanse-app\\exokit\\node_modules\\window-fetch\\lib\
\index.js:1289:16)\n    at ClientRequest.emit (events.js:182:13)\n    at ClientRequest.EventEmitter.emit (domain.js:442:20)\n    at TLSSocket.socketErrorListener (_http_client.js:382:9)\n    at TLSSocket.emit (event
s.js:182:13)\n    at TLSSocket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback
 (internal/process/next_tick.js:63:19)' }
{ Error: connect ETIMEDOUT 104.25.104.6:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '104.25.104.6',
  port: 443 }
{ Error: connect ETIMEDOUT 5.9.124.40:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '5.9.124.40',
  port: 443 }
{ Error: connect ETIMEDOUT 5.9.124.40:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '5.9.124.40',
  port: 443 }
{ Error: connect ETIMEDOUT 5.9.124.40:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '5.9.124.40',
  port: 443 }
{ Error: connect ETIMEDOUT 5.9.124.40:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '5.9.124.40',
  port: 443 }
{ Error: connect ETIMEDOUT 5.9.124.40:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '5.9.124.40',
  port: 443 }
{ Error: connect ETIMEDOUT 5.9.124.40:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '5.9.124.40',
  port: 443 }
Bugsnag:  Encountered an uncaught error, terminating…
Error: connect ETIMEDOUT 104.25.104.6:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1163:14)

```

**Comment by modulesio** [comment]
Apparently the best repro for this is the remote A-Painter URL; using `localhost` makes the timeouts less likely.

**Comment by shaneharris** [comment]
I actually couldnt get it to timeout at all on localhost
more evidence:
```
ErrorEvent {
  type: 'error',
  target: <img src="assets/models/../images/logo.png"/>,
  bubbles: false,
  cancelable: false,
  defaultPrevented: false,
  propagationStopped: false,
  currentTarget: <img src="assets/models/../images/logo.png"/>,
  message:
   'request to https://aframe.io/a-painter/assets/images/logo.png failed, reason: connect ETIMEDOUT 104.25.105.6:443',
  stack:
   'FetchError: request to https://aframe.io/a-painter/assets/images/logo.png failed, reason: connect ETIMEDOUT 104.25.105.6:443\n    at ClientRequest.<anonymous> (c:\\exokit\\node_modules\\window-fetch\\lib\\index.js:1289:16)\n    at ClientRequest.emit (events.js:182:13)\n    at ClientRequest.EventEmitter.emit (domain.js:442:20)\n    at TLSSocket.socketErrorListener (_http_client.js:382:9)\n    at TLSSocket.emit (events.js:182:13)\n    at TLSSocket.EventEmitter.emit (domain.js:442:20)\n    at emitErrorNT (internal/streams/destroy.js:82:8)\n    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)\n    at process._tickCallback (internal/process/next_tick.js:63:19)' }
```

**Comment by shaneharris** [comment]
another url to test- https://xactaccounts.co.uk/Test3/gltf.html 

It doesn't seem to load the model assets. Pretty consistently reproducible. Loads fine in the browser.

**Comment by shaneharris** [comment]
ive been doing some more research on the ETIMEDOUT error.
so it it the GLTF model assets causing it for sure.(edited)
i temporarily disbale it and the timeouts stop. I think that file has a large volume of textures like ~200
it seems every connection made the response headers always have connection: close
i think the volume of connections is causing the timeouts, but no matter what i do the connection will not go to keep-alive.
it is keep-alive in the browser
im using nginx to serve that model, and i even explicitly set the connection header with add_header Connection keep-alive and i then in the response i get connection: close, keep-alive
its like no matter what i do the keepalive is not respected.
around here - https://github.com/modulesio/window-fetch/blob/1da44f0677e720a83610c76a1f39d9f72bbec1ee/src/index.js#L46

i hacked in the line options.agent = (options.protocol === 'https:' ? new https.Agent({keepAlive:true}) : new http.Agent({keepAlive:true}))
and i realise that window-fetch is based on node-fetch going by the test shown in this issue - https://github.com/bitinn/node-fetch/issues/423

i should expect to see the keep-alive header int he response if using the http agent like that.
anyway i just said i would let you know what i had discovered.
but it def feels like a max connections issue, possibly solvable if keep-alive would work .

**Comment by shaneharris** [comment]
OK so I wrapped the inner fetch in the constructor of `HTMLImageElement` in a `setTimeout(()=>{},10*count)` and it got around the issue. It seems its a system bottleneck as I was also logging the response statusCode in `window-fetch` and it was always 200.

**Comment by modulesio** [comment]
That seems pretty close to the ideal solution to me, which is queuing resources to limit extreme concurrency to a request cap rather than a time guess.

From this data it looks like there are simply too many things downloading at once.

I’ll try to get in a fix that covers all resource types without any setTimeout, but rather a concurrency-buffered fifo.
