### ISSUE TITLE
HTMLInputElement missing

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#299]
Repro: https://shaneharris.github.io/aframe-material-collection/

Lifecycle library is not connected.
A-Frame Version: 0.8.0 (Date 2018-03-11, Commit #82934b02)
three Version: github:dmarcos/three.js#r90fixPose
WebVR Polyfill Version: ^0.9.40
aframe-material-collection version 0.2.7
core:schema:warn Default value `default` does not match type `boolean` in component `ui-yoga`
core:schema:warn Default value `default` does not match type `int` in component `ui-yoga`
core:schema:warn Default value `default` does not match type `int` in component `ui-yoga`
core:schema:warn Default value `default` does not match type `int` in component `ui-yoga`
core:schema:warn Default value `default` does not match type `int` in component `ui-yoga`
core:schema:warn Default value `default` does not match type `boolean` in component `ui-yoga`
core:schema:warn Default value `default` does not match type `boolean` in component `ui-yoga`
THREE.WebGLRenderer 90
THREE.WebGLRenderer: .shadowMap.renderReverseSided has been removed. Set Material.shadowSide instead.
THREE.WebGLRenderer: .shadowMap.renderSingleSided has been removed. Set Material.shadowSide instead.
TypeError: Cannot read property 'width' of undefined
    at window.CanvasInput.render (https://cdn.rawgit.com/shaneharris/CanvasInput/master/CanvasInput.js:1072:38)
    at new window.CanvasInput (https://cdn.rawgit.com/shaneharris/CanvasInput/master/CanvasInput.js:176:10)
    at i.setupCanvasInput (aframe-material-collection.js:13163:40)
    at i.setValue (aframe-material-collection.js:13047:14)
    at init (aframe-material-collection.js:13015:14)
    at i.updateProperties (https://aframe.io/releases/0.8.0/aframe.min.js:477:3547)
    at i.module.exports.Component (https://aframe.io/releases/0.8.0/aframe.min.js:477:1683)
    at new i (https://aframe.io/releases/0.8.0/aframe.min.js:477:6186)
    at HTMLElement.value (https://aframe.io/releases/0.8.0/aframe.min.js:286:4370)
    at HTMLElement.value (https://aframe.io/releases/0.8.0/aframe.min.js:286:6034)

**Comment by modulesio** [comment]
Throwing library: https://github.com/shaneharris/CanvasInput

**Comment by shaneharris** [comment]
This is no longer a dependency so this is up to you if its needed. I think the less dom the better!
