### ISSUE TITLE
Loading non-MR site should throw error

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#32]
Currently loading e.g. `http://youtube.com/` will lock up the browser, but it should instead display an error in MR.

```
TypeError: Cannot read property 'responseStart' of undefined
    at http://youtube.com/:1:1807
    at http://youtube.com/:1:2575
    at _runJavascript (C:\Users\avaer\Documents\GitHub\exokit\core.js:3215:15)
    at HTMLScriptElement.on.innerHTML (C:\Users\avaer\Documents\GitHub\exokit\core.js:2486:9)
    at HTMLScriptElement.emit (events.js:182:13)
    at HTMLScriptElement.EventEmitter.emit (domain.js:442:20)
    at HTMLScriptElement._emit (C:\Users\avaer\Documents\GitHub\exokit\core.js:1343:40)
    at HTMLScriptElement.set innerHTML [as innerHTML] (C:\Users\avaer\Documents\GitHub\exokit\core.js:2528:10)
    at HTMLScriptElement.run (C:\Users\avaer\Documents\GitHub\exokit\core.js:2549:24)
    at element.traverseAsync (C:\Users\avaer\Documents\GitHub\exokit\core.js:3186:16)
```

**Comment by shawwn** [comment]
If it locks up the browser, that’s probably a legit bug separate from this issue.
