### ISSUE TITLE
Electron example: ImageData: Invalid array length

### ISSUE THREAD

**Issue by shaneharris** [webmixedreality/exokit#334]
It seems to paint the first few frames OK then fails. The array length looks valid to me i.e an int less than 4294967296 and not negative. 

Node: v10.8.0
OS: Windows 10 Pro x64
Exokit: 0.0.432

Log output: 

```
c:\workspace\exokit>node . -l http://localhost:8080/electron.html
THREE.WebGLRenderer 95

paint 5504000
got bytelength 5504000 1600 860 5504000
loaded
paint 5504000
got bytelength 5504000 1600 860 5504000
paint 627200
got bytelength 627200 1600 98 627200
paint 1633320
got bytelength 1633320 330 256 337920
Error: ImageData: Invalid array length
    at BrowserWindow.browserWindow.on.o (http://localhost:8080/electron.html:79:30)
    at BrowserWindow.emit (events.js:182:13)
    at BrowserWindow.EventEmitter.emit (domain.js:442:20)
    at EventEmitter.messageEmitter.on.m (c:\workspace\exokit\src\electron.js:227:37)
    at EventEmitter.emit (events.js:182:13)
    at EventEmitter.emit (domain.js:442:20)
    at Client.localChannel.on.data (c:\workspace\exokit\src\electron.js:97:32)
    at Client.emit (c:\workspace\exokit\node_modules\event-pubsub\es5.js:74:21)
    at Socket.<anonymous> (c:\workspace\exokit\node_modules\node-ipc\dao\client.js:210:24)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:260:13)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at Pipe.onread (net.js:639:20)

```

**Comment by modulesio** [comment]
Thanks! Managed to repro this by switching the url to `https://facebook.com`

Probably an IPC problem; investigating 👀.

**Comment by modulesio** [comment]
I'm also seeing cases where the electron API is giving us back oversized buffers.

I'm thinking the correct behavior is for ImageData to accept these as long as they as _sufficiently_ sized...
