### ISSUE TITLE
libopenvr_api.so missing (linux)

### ISSUE THREAD

**Issue by phil294** [webmixedreality/exokit#34]
Ran the install script with  (X)Ubuntu 16.04 xenial x86_64 Linux 4.4.0-122-generic. Extracted the files just fine, when running `exokit` however some OpenVR library is missing. Is this expected? Didnt see any prerequisite requirements in the readme.

```
internal/modules/cjs/loader.js:707
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^
Error: libopenvr_api.so: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:707:18)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/exokit/native-bindings.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
```

**Comment by modulesio** [comment]
Thanks! Seems like it would be an `rpath` issue or similar.

**Comment by modulesio** [comment]
Very similar style of issue: https://github.com/webmixedreality/exokit/issues/25

**Comment by modulesio** [comment]
> Is this expected?

Nope, it's a bug. We include openvr.so via [this module](https://github.com/modulesio/node-native-openvr-deps); it's [in the `package.json` in this repo](https://github.com/webmixedreality/exokit/blob/master/package.json#L54).

I suspect this one is a regression. Not too long ago we changed the way the bindings are built and linked in the `binding.gyp`.

https://github.com/webmixedreality/exokit/commit/86c30094668f8290fcea78d8c904128301cab1a6#diff-21e418851ae48f9b11907837add9e39a
https://github.com/webmixedreality/exokit/commit/bcdd6b1769447e0d1862aef28ecf5b682cec8cd7#diff-21e418851ae48f9b11907837add9e39a

`git bisect` might prove fruitful.

My hunch is that the fix would probably be in `binding.gyp`.

**Comment by chrislatorres** [comment]
Tested on Ubuntu 18.04, confirmed fix.
