### ISSUE TITLE
Cannot read property 'IsPresent' of undefined

### ISSUE THREAD

**Issue by chrislatorres** [webmixedreality/exokit#418]
Exokit 0.0.447
Ubuntu 18.04
`node . -h`

```
TypeError: Cannot read property 'IsPresent' of undefined
    at XR.requestDevice (/home/username/github/exokit/src/XR.js:24:92)
    at _updateDisplays (file:///home/username/github/exokit/node_modules/exokit-home/index.html:2632:51)
    at file:///home/username/github/exokit/node_modules/exokit-home/index.html:2645:5
    at file:///home/username/github/exokit/node_modules/exokit-home/index.html:3257:3
    at Object._runJavascript (/home/username/github/exokit/src/utils.js:67:15)
    at HTMLScriptElement.runNow (/home/username/github/exokit/src/DOM.js:1597:11)
    at HTMLScriptElement.<anonymous> (/home/username/github/exokit/src/DOM.js:1616:21)
    at /home/username/github/exokit/src/Document.js:110:17
    at _addRun (/home/username/github/exokit/src/Document.js:124:7)
    at /home/username/github/exokit/src/Document.js:117:11
```

**Comment by chrislatorres** [comment]
This error happens upon running `node . -h` and freezes the home app.

**Comment by chrislatorres** [comment]
Commenting out 
https://github.com/webmixedreality/exokit-home/blob/7f1247b45cbf98d370b0a6b3228617c7a3b0ef9f/index.html#L2632-L2633
fixes the problem, looks like 
https://github.com/webmixedreality/exokit/blob/0d28e1e6104616186ac1da6afb640f16bf68a5d7/deps/exokit-bindings/magicleap/src/magicleap.cc#L70

is not accessible

**Comment by modulesio** [comment]
I think [this `console.log`](https://github.com/webmixedreality/exokit/issues/418#L24) is pointless and can be deleted.
