### ISSUE TITLE
User space throw causes main loop termination

### ISSUE THREAD

**Issue by chrislatorres** [webmixedreality/exokit#447]
URL: `https://extent.network/user-space/user-space.html`

Crash when trying to run site in Exokit to emulate VR.

Running:
Ubuntu 18.04
Exokit 0.0.452

```
$ exokit https://extent.network/user-space/user-space.html 
THREE.WebGLRenderer 95
ReferenceError: name is not defined
    at requestUsers (server-connection.js:45:52)
    at update (user-space.js:97:5)
    at onAnimationFrame (js/three.js:22685:36)
    at onAnimationFrame (js/three.js:7424:4)
    at tickAnimationFrame (/usr/local/lib/exokit/core.js:691:9)
    at Timeout._recurse [as _onTimeout] (/usr/local/lib/exokit/index.js:1359:12)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
Bugsnag:  Encountered an uncaught error, terminating…
ReferenceError: name is not defined
    at requestUsers (server-connection.js:45:52)
    at update (user-space.js:97:5)
    at onAnimationFrame (js/three.js:22685:36)
    at onAnimationFrame (js/three.js:7424:4)
    at tickAnimationFrame (/usr/local/lib/exokit/core.js:691:9)
    at Timeout._recurse [as _onTimeout] (/usr/local/lib/exokit/index.js:1359:12)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
    at Timer.processTimers (timers.js:212:10)
```

![screenshot from 2018-09-09 19-40-40](https://user-images.githubusercontent.com/29695350/45270972-9d181600-b468-11e8-8a89-4a262ee10f69.png)

**Comment by cmdrflexo** [comment]
thanks for bringing that up. :D
problem with the app, not exokit though.

**Comment by modulesio** [comment]
Yeah this looks like a site issue. However, we probably shouldn't be crashing if the tick throws.

I think for cases like this we should catch from user code and default to a log but chug on, like Chrome/Firefox would.

**Comment by ngokevin** [comment]
Does not all user code already catch? What's missing?

**Comment by modulesio** [comment]
I think the `requestAnimationFrame` callbacks aren't under a try-catch wrap: https://github.com/webmixedreality/exokit/blob/a2a647d686dd45c8271f942ed6ced5e17ab50d83/core.js#L679

This won't cause a server termination [due to `process.on('uncaughtException')`](https://github.com/webmixedreality/exokit/blob/a2a647d686dd45c8271f942ed6ced5e17ab50d83/index.js#L1631), but it probably would unwind the mainloop.

I think the solution might be to wrap the raf callbacks in a `try-catch-warn` and keep going.
