### ISSUE TITLE
WebAudio::AudioParam setValueAtTime

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#457]
Hitting this on https://extent.network/audio-viz-demo/av-demo.html

```
[x] https://extent.network/audio-viz-demo/av-demo.html
undefined
[x] THREE.WebGLRenderer 95
starting audio
THREE.FBXLoader: FBX binary version: 7400
TypeError: Cannot read property 'setValueAtTime' of undefined
    at Audio.play (js/three.js:39709:24)
    at _playAmbient (_SANDBOX.js:114:56)
    at update (user-space.js:110:40)
    at onAnimationFrame (js/three.js:22685:36)
    at onAnimationFrame (js/three.js:7424:4)
    at tickAnimationFrame (C:\exokit\core.js:678:9)
    at Timeout._recurse [as _onTimeout] (C:\exokit\index.js:1276:12)
    at ontimeout (timers.js:427:11)
    at tryOnTimeout (timers.js:289:5)
    at listOnTimeout (timers.js:252:5)
```

**Comment by paperkettle** [comment]
Similar error here on a Magic Leap 

```
09-13 19:29:34.909  2529     6 I exokit  : TypeError: Cannot read property 'setValueAtTime' of undefined
09-13 19:29:34.909  2529     6 I exokit  :     at Cn.play (https://aframe.io/releases/0.8.2/aframe.min.js:112:19861)
09-13 19:29:34.909  2529     6 I exokit  :     at https://aframe.io/releases/0.8.2/aframe.min.js:214:3045
09-13 19:29:34.909  2529     6 I exokit  :     at Array.forEach (<anonymous>)
09-13 19:29:34.909  2529     6 I exokit  :     at i.playSound (https://aframe.io/releases/0.8.2/aframe.min.js:214:2986)
09-13 19:29:34.909  2529     6 I exokit  :     at HTMLElement.<anonymous> (https://aframe.io/releases/0.8.2/aframe.min.js:379:132)
09-13 19:29:34.909  2529     6 I exokit  :     at HTMLElement.emit (events.js:187:15)
09-13 19:29:34.909  2529     6 I exokit  :     at HTMLElement.EventEmitter.emit (domain.js:442:20)
09-13 19:29:34.909  2529     6 I exokit  :     at HTMLElement._emit (/package/src/Event.js:56:40)
09-13 19:29:34.909  2529     6 I exokit  :     at _emit (/package/src/Event.js:34:14)
09-13 19:29:34.909  2529     6 I exokit  :     at _recurse (/package/src/Event.js:42:7)

```

https://exokit-sound-woes.glitch.me
https://glitch.com/edit/#!/exokit-sound-woes

Sound plays in Chrome when cursor enters cube, but I get that error on Exokit console

**Comment by modulesio** [comment]
Yeah this looks like just a missing WebAudio method, not platform specific.

**Comment by chrislatorres** [comment]
Exokit v0.0.517
Ubuntu 18.04
Node v11.10.1

--------------------------------------------------

Command ran: `exokit -x webvr https://supermedium.github.io/supersays/src/`
  
--------------------------------------------------
  
```
$ exokit -x webvr https://supermedium.github.io/supersays/src/
A-Frame Version: 0.8.1 (Date 2018-04-10, Commit #87d3d23)
three Version: github:supermedium/three.js#r90fixPoseAndRaycaster
WebVR Polyfill Version: ^0.10.5
THREE.WebGLRenderer 90
[2019-03-06T01:15:20.792Z]  @firebase/database: FIREBASE WARNING: Using an unspecified index. Your data will be downloaded and filtered on the client. Consider adding ".indexOn": "score" at /scores to your security rules for better performance. 
[2019-03-06T01:15:20.800Z]  @firebase/database: FIREBASE WARNING: Exception was thrown by user callback. TypeError: Cannot read property 'setValueAtTime' of undefined
    at Cn.play (https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:112:19861)
    at https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:214:3045
    at Array.forEach (<anonymous>)
    at i.playSound (https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:214:2986)
    at i.playSound (https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:379:132)
    at i.updateScore (components/highscores.js:28:65)
    at https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:119620
    at Object.t.exceptionGuard (https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:5214)
    at e.raise (https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:155072)
    at e.li (https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:154725) 
TypeError: Cannot read property 'setValueAtTime' of undefined
    at Cn.play (https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:112:19861)
    at https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:214:3045
    at Array.forEach (<anonymous>)
    at i.playSound (https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:214:2986)
    at i.playSound (https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:379:132)
    at i.updateScore (components/highscores.js:28:65)
    at https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:119620
    at Object.t.exceptionGuard (https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:5214)
    at e.raise (https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:155072)
    at e.li (https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:154725)
Bugsnag:  Encountered an uncaught error, terminating…
TypeError: Cannot read property 'setValueAtTime' of undefined
    at Cn.play (https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:112:19861)
    at https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:214:3045
    at Array.forEach (<anonymous>)
    at i.playSound (https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:214:2986)
    at i.playSound (https://rawgit.com/aframevr/aframe/c4aa63e/dist/aframe-master.min.js:379:132)
    at i.updateScore (components/highscores.js:28:65)
    at https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:119620
    at Object.t.exceptionGuard (https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:5214)
    at e.raise (https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:155072)
    at e.li (https://www.gstatic.com/firebasejs/4.12.1/firebase.js:34:154725)
```

**Comment by chrislatorres** [comment]
Exokit v0.0.517
Ubuntu 18.04
Node v11.10.1

--------------------------------------------------

Command ran: `exokit https://towermax.fitness/tower/`
  
--------------------------------------------------

```
TypeError: Cannot read property 'setValueAtTime' of undefined
    at Xn.play (js/aframe7.min.js:117:3362)
    at js/aframe7.min.js:262:3024
    at Array.forEach (<anonymous>)
    at i.playSound (js/aframe7.min.js:262:2965)
    at i.playSound (js/aframe7.min.js:427:132)
    at viewScreens (js/jquery.mobile-1.4.5.min.js:1:160542)
    at setMenuBG (js/jquery.mobile-1.4.5.min.js:1:136452)
    at js/jquery.mobile-1.4.5.min.js:1:233527
    at listOnTimeout (timers.js:326:17)
    at processTimers (timers.js:268:5)
Bugsnag:  Encountered an uncaught error, terminating…
TypeError: Cannot read property 'setValueAtTime' of undefined
    at Xn.play (js/aframe7.min.js:117:3362)
    at js/aframe7.min.js:262:3024
    at Array.forEach (<anonymous>)
    at i.playSound (js/aframe7.min.js:262:2965)
    at i.playSound (js/aframe7.min.js:427:132)
    at viewScreens (js/jquery.mobile-1.4.5.min.js:1:160542)
    at setMenuBG (js/jquery.mobile-1.4.5.min.js:1:136452)
    at js/jquery.mobile-1.4.5.min.js:1:233527
    at listOnTimeout (timers.js:326:17)
    at processTimers (timers.js:268:5)
```
