### ISSUE TITLE
Worker setImmediate missing

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#497]
On Windows, when loading a site that has an `https` worker script, `_tls_wrap` will throw on missing `setImmediate`. This probably means the worker did not load the worker bootstrap script correctly.

```
TypeError: setImmediate is not a function
       at TLSSocket.onSocketCloseDestroySSL (_tls_wrap.js:451:3)
       at TLSSocket.emit (events.js:187:15)
       at _handle.close (net.js:599:12)
       at TCP.done (_tls_wrap.js:384:7)
       at getScript (C:\Users\avaer\Documents\GitHub\exokit\node_modules\window-worker\src\worker.js:82:32)
       at C:\Users\avaer\Documents\GitHub\exokit\node_modules\window-worker\src\worker.js:100:17
       at onmessage (C:\Users\avaer\Documents\GitHub\exokit\node_modules\window-worker\src\worker.js:176:5)
       at onthreadmessage (C:\Users\avaer\Documents\GitHub\exokit\node_modules\child-process-thread\child.js:14:5)
       at getScript (C:\Users\avaer\Documents\GitHub\exokit\node_modules\window-worker\src\worker.js:94:17)
       at C:\Users\avaer\Documents\GitHub\exokit\node_modules\window-worker\src\worker.js:100:17
       at onmessage (C:\Users\avaer\Documents\GitHub\exokit\node_modules\window-worker\src\worker.js:176:5)
       at onthreadmessage (C:\Users\avaer\Documents\GitHub\exokit\node_modules\child-process-thread\child.js:14:5)
```

Repo was on `3data.io`.

**Comment by modulesio** [comment]
Note to self: this also blocks Hydra `exotest`

**Comment by modulesio** [comment]
I think I figured it out, this was

**Comment by 3DataWill** [comment]
We're still seeing what appears to the same error. Exokit v0.0.481 on Magic Leap (Lumin OS ver 0.92.0)

```
10-03 14:25:16.623  2212     6 I exokit  : ErrorEvent {
10-03 14:25:16.623  2212     6 I exokit  :   error:
10-03 14:25:16.623  2212     6 I exokit  :    TypeError: setImmediate is not a function
10-03 14:25:16.623  2212     6 I exokit  :        at TLSSocket.onSocketCloseDestroySSL (_tls_wrap.js:451:3)
10-03 14:25:16.623  2212     6 I exokit  :        at TLSSocket.emit (events.js:187:15)
10-03 14:25:16.623  2212     6 I exokit  :        at _handle.close (net.js:599:12)
10-03 14:25:16.623  2212     6 I exokit  :        at TCP.done (_tls_wrap.js:384:7)
10-03 14:25:16.623  2212     6 I exokit  :        at getScript (/package/node_modules/window-worker/src/worker.js:72:30)
10-03 14:25:16.623  2212     6 I exokit  :        at /package/node_modules/window-worker/src/worker.js:84:17
10-03 14:25:16.623  2212     6 I exokit  :        at onmessage (/package/node_modules/window-worker/src/worker.js:159:5)
10-03 14:25:16.623  2212     6 I exokit  :        at onthreadmessage (/package/node_modules/child-process-thread/child.js:14:5),
10-03 14:25:16.623  2212     6 I exokit  :   message: 'setImmediate is not a function',
10-03 14:25:16.623  2212     6 I exokit  :   filename: '_tls_wrap.js',
10-03 14:25:16.623  2212     6 I exokit  :   lineno: 451 }
```

**Comment by modulesio** [comment]
Thanks, is there a public repro for this?
