### ISSUE TITLE
npm build error

### ISSUE THREAD

**Issue by cmdrflexo** [webmixedreality/exokit#515]
Build error with `npm install` on latest exokit-master
```
Creating library E:\Projects\Exokit\exokit\exokit-master\build\Release\exokit.lib and object E:\Projects\Exokit\ex
  okit\exokit-master\build\Release\exokit.exp
skia.lib(skia.SkRasterPipeline.obj) : error LNK2001: unresolved external symbol __std_reverse_trivially_swappable_8 [E:
\Projects\Exokit\exokit\exokit-master\build\exokit.vcxproj]
E:\Projects\Exokit\exokit\exokit-master\build\Release\exokit.node : fatal error LNK1120: 1 unresolved externals [E:\Pro
jects\Exokit\exokit\exokit-master\build\exokit.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd E:\Projects\Exokit\exokit\exokit-master
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! exokit@0.0.481 install: `node ./scripts/preinstall.js && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the exokit@0.0.481 install script.
```

[2018-10-01T15_58_41_685Z-debug.log](https://github.com/webmixedreality/exokit/files/2434721/2018-10-01T15_58_41_685Z-debug.log)

![image](https://user-images.githubusercontent.com/4148613/46300626-31f6c680-c572-11e8-8356-38f16c36054e.png)

**Comment by cmdrflexo** [comment]
Upgraded node and ran install from 2017 dev command prompt

![image](https://user-images.githubusercontent.com/4148613/46304230-1b556d00-c57c-11e8-97a0-c19e47c315e4.png)

**Comment by modulesio** [comment]
The full log would be helpful, as well as the node-gyp autodetection log.

I still suspect it’s a compiler version mismatch.

**Comment by cmdrflexo** [comment]
used `npm config set msvs_version 2017` and was able to complete build
[https://github.com/nodejs/node-gyp/issues/1278](url)
