### ISSUE TITLE
web workers not workering - EBADF: bad file descriptor

### ISSUE THREAD

**Issue by shaneharris** [webmixedreality/exokit#574]
Maybe i should raise this over here -  https://github.com/modulesio/window-worker

it looks like  web workers are broken with the following output:

```c:\exokit>node . https://sordid-asparagus.glitch.me/
{ [Error: EBADF: bad file descriptor, read] errno: -4083, code: 'EBADF', syscall: 'read' }
{ [Error: EBADF: bad file descriptor, close] errno: -4083, code: 'EBADF', syscall: 'close' }
ErrorEvent {
  error:
   Error: EBADF: bad file descriptor, write
       at Object.writeSync (fs.js:564:3)
       at createRequest (c:\exokit\node_modules\window-worker\src\worker.js:24:8)
       at getScript (c:\exokit\node_modules\window-worker\src\worker.js:97:33)
       at c:\exokit\node_modules\window-worker\src\worker.js:124:17
       at onmessage (c:\exokit\node_modules\window-worker\src\worker.js:202:5)
       at onthreadmessage (c:\exokit\node_modules\child-process-thread\child.js:14:5),
  message: 'EBADF: bad file descriptor, write',
  filename: 'fs.js',
  lineno: 564 }
Bugsnag:  Encountered an uncaught error, terminating…
Error: EBADF: bad file descriptor, close
```

You can visit this glitch to test - https://sordid-asparagus.glitch.me/, it has a bare bones web worker example.

**Comment by modulesio** [comment]
Interesting, is this windows?

**Comment by modulesio** [comment]
This is probably the pipe() implementation on win32.

**Comment by modulesio** [comment]
At this point it might make sense to do workers via node’s new worker APIs rather than window-worker.

**Comment by modulesio** [comment]
The reason windup-worked exists is all of the alternatives are missing a ton of features like importScripts, transferables, forklessness, url/blob support, native re-require, and probably more I forgot.

The window-worker fix is to fix blocking pipes on windows. Or we could sidestep the need for them by doing the synchronous piping inside the worker itself with native node workers.

**Comment by shaneharris** [comment]
how would we do the synchronous piping inside the worker? do you mean the calls to fs.writeSync?

**Comment by modulesio** [comment]
`fs.readSync`, but yes.

**Comment by shaneharris** [comment]
i can confirm this is now workering again ;)
