### ISSUE TITLE
Local file query string ENOENT

### ISSUE THREAD

**Issue by NoahSchiffman** [webmixedreality/exokit#594]
Here I got this error log when I tried to launch realitytabs.html  on a debian derivative of Linux using 18.04 called peppermint os here's the log:

`noah-a-s@TheGoldenLeaper ~/Desktop/exokit $ node . examples/realitytabs.html
ErrorEvent {
  type: 'error',
  target: <script src="three.js?tab=top"></script>,
  bubbles: false,
  cancelable: false,
  defaultPrevented: false,
  propagationStopped: false,
  currentTarget: <script src="three.js?tab=top"></script>,
  message:
   'ENOENT: no such file or directory, open \'/home/noah-a-s/Desktop/exokit/examples/three.js?tab=top\'',
  stack:
   'Error: ENOENT: no such file or directory, open \'/home/noah-a-s/Desktop/exokit/examples/three.js?tab=top\'' }
Error: ENOENT: no such file or directory, open '/home/noah-a-s/Desktop/exokit/examples/three.js?tab=top'
ReferenceError: THREE is not defined
    at fakeDisplay.js:3:21
    at fakeDisplay.js:197:3
    at Object._runJavascript (/home/noah-a-s/Desktop/exokit/src/utils.js:67:15)
    at ownerDocument.defaultView.fetch.then.then.s (/home/noah-a-s/Desktop/exokit/src/DOM.js:1609:17)
ReferenceError: THREE is not defined
    at file:///home/noah-a-s/Desktop/exokit/examples/realitytabs.html:12:29
    at Object._runJavascript (/home/noah-a-s/Desktop/exokit/src/utils.js:67:15)
    at Resource.ownerDocument.resources.addResource [as getCb] (/home/noah-a-s/Desktop/exokit/src/DOM.js:1637:13)
    at Promise (/home/noah-a-s/Desktop/exokit/src/core.js:101:12)
    at new Promise (<anonymous>)
    at Resource.get (/home/noah-a-s/Desktop/exokit/src/core.js:100:12)
    at Resources.drain (/home/noah-a-s/Desktop/exokit/src/core.js:179:16)
    at Promise (/home/noah-a-s/Desktop/exokit/src/core.js:172:12)
    at new Promise (<anonymous>)
    at Resources.addResource (/home/noah-a-s/Desktop/exokit/src/core.js:152:12)`

![image](https://user-images.githubusercontent.com/37890940/48239779-1955a980-e385-11e8-8655-0874c6fa0c9f.png)

**Comment by chrislatorres** [comment]
Closing this issue due to being outdated.
