### ISSUE TITLE
Form Data with Blobs - TypeError: source.on is not a function

### ISSUE THREAD

**Issue by shaneharris** [webmixedreality/exokit#627]
Adding a blob to form data produces the following error:

`node . -x none https://childlike-serpent.glitch.me/`

```
A-Frame Version: 0.8.0 (Date 2018-03-11, Commit #82934b02)
three Version: github:dmarcos/three.js#r90fixPose
WebVR Polyfill Version: ^0.9.40
THREE.WebGLRenderer 90
THREE.WebGLRenderer: .shadowMap.renderReverseSided has been removed. Set Material.shadowSide instead.
THREE.WebGLRenderer: .shadowMap.renderSingleSided has been removed. Set Material.shadowSide instead.
TypeError: source.on is not a function
    at Function.DelayedStream.create (C:\workspace\expanse-app\exokit\node_modules\delayed-stream\lib\delayed_stream.js:33:10)
    at FormData.CombinedStream.append (C:\workspace\expanse-app\exokit\node_modules\combined-stream\lib\combined_stream.js:44:37)
    at FormData.append (C:\workspace\expanse-app\exokit\node_modules\form-data\lib\form_data.js:74:3)
    at https://childlike-serpent.glitch.me/:16:14
    at Object._runJavascript (C:\workspace\expanse-app\exokit\src\utils.js:67:15)
    at Resource.ownerDocument.resources.addResource [as getCb] (C:\workspace\expanse-app\exokit\src\DOM.js:1639:13)
    at Promise (C:\workspace\expanse-app\exokit\src\core.js:92:12)
    at new Promise (<anonymous>)
    at Resource.get (C:\workspace\expanse-app\exokit\src\core.js:91:12)
    at Resources.drain (C:\workspace\expanse-app\exokit\src\core.js:170:16)
    at Promise (C:\workspace\expanse-app\exokit\src\core.js:163:12)
    at new Promise (<anonymous>)
    at Resources.addResource (C:\workspace\expanse-app\exokit\src\core.js:143:12)
    at HTMLScriptElement.runNow (C:\workspace\expanse-app\exokit\src\DOM.js:1638:41)
    at HTMLScriptElement.<anonymous> (C:\workspace\expanse-app\exokit\src\DOM.js:1655:21)
    at C:\workspace\expanse-app\exokit\src\Document.js:120:17
    at Document._addRun (C:\workspace\expanse-app\exokit\src\Document.js:134:7)
    at element.traverse.el (C:\workspace\expanse-app\exokit\src\core.js:664:41)
    at _recurse (C:\workspace\expanse-app\exokit\src\DOM.js:1118:22)
    at _recurse (C:\workspace\expanse-app\exokit\src\DOM.js:1124:28)
    at HTMLBodyElement.traverse (C:\workspace\expanse-app\exokit\src\DOM.js:1135:12)
    at Promise (C:\workspace\expanse-app\exokit\src\core.js:657:15)
    at new Promise (<anonymous>)
    at Object._runHtml (C:\workspace\expanse-app\exokit\src\core.js:654:12)
    at process.nextTick (C:\workspace\expanse-app\exokit\src\Document.js:176:29)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Not sure if this one is in the scope. I could work around by posting strings instead of files/blobs.

**Comment by modulesio** [comment]
It's in scope, but node supports neither `Blob` nor `FormData` and we source them from different repos and they don't play with each other.

The root of the bug is that the [`FormData` implementation]() has no concept of `Blob` and therefore no `Blob` support.

**Comment by modulesio** [comment]
According to my research forking the `FormData` implementation and pulling off the `.buffer` from the `Blob` [here](https://github.com/form-data/form-data/blob/master/lib/form_data.js#L58) should work.

**Comment by shaneharris** [comment]
I actually was trying that myself with something along the lines of;

```
if(value.buffer&&Buffer.isBuffer(value.buffer)){
  value = value.buffer;
}
```
It was truncating the string that was uploaded and i couldn't figure out why - maybe the buffer length was too short.

I have since reverted to sending the data as strings in the form data.

**Comment by modulesio** [comment]
Interesting, how was this Blob acquired? Was it large (e.g megabytes)?

**Comment by modulesio** [comment]
It could be that [this check](https://github.com/modulesio/window-form-data/blob/master/lib/form_data.js#L92) was't passing -- quite likely if the prototype wasn't mutated to normalize to outer the `global` as we have to do for all typed array views pre-node 11.

**Comment by shaneharris** [comment]
Sorry i missed this somhow, so the blob size would have been pretty small but could get large. The one i was testing with would have been kilobytes.

I had thought it was the below failing too. 
```
Buffer.isBuffer(value)
```
so i tried 
```
Buffer.isBuffer(value.buffer) // The blob has a buffer inside
```
but it didnt work. I got the data but it was always truncated. I could not figure out why.

**Comment by modulesio** [comment]
Yeah I think it should be solved by https://github.com/webmixedreality/exokit/pull/628. It was a Buffer identity check that elided a length set.
