### ISSUE TITLE
Elf does not load from rawgit

### ISSUE THREAD

**Issue by modulesio** [webmixedreality/exokit#69]
https://rawgit.com/ChrisEddy/exokit-three.js-example-library/master/three.js-dev/examples/webgl_loader_collada.html

```
Error
    at Console.console.error (window-start-script.js:11:20)
    at Scene.add (../build/three.js:8166:13)
    at LoadingManager.onLoad (https://rawgit.com/ChrisEddy/exokit-three.js-example-library/master/three.js-dev/examples/webgl_loader_collada.html:71:12)
    at LoadingManager.itemEnd (../build/three.js:30590:12)
    at XMLHttpRequest.<anonymous> (../build/three.js:30842:21)
    at handleListener (C:\Users\avaer\Documents\GitHub\exokit\node_modules\window-xhr\lib\eventtarget.js:91:23)
    at Array.some (<anonymous>)
    at XMLHttpRequest._invoke (C:\Users\avaer\Documents\GitHub\exokit\node_modules\window-xhr\lib\eventtarget.js:89:20)
    at XMLHttpRequest._dispatch (C:\Users\avaer\Documents\GitHub\exokit\node_modules\window-xhr\lib\eventtarget.js:109:13)
    at XMLHttpRequest.dispatchEvent (C:\Users\avaer\Documents\GitHub\exokit\node_modules\window-xhr\lib\eventtarget.js:152:22)
```

**Comment by modulesio** [comment]
Fixed!

![capture 5](https://user-images.githubusercontent.com/6926057/40585212-a6092cfc-617c-11e8-987e-a85768d6ccdb.PNG)
