### ISSUE TITLE
Cannot find module './build/Release/vm_one.node'

### ISSUE THREAD

**Issue by Palmer-JC** [webmixedreality/exokit#720]
System:
Window 10
node version: 10.15.0
GPU: nVidia GTX 1050

exokit: 0.505

---
ran npm install, and build directory was built

---
`.\scripts\exokit  https:/myUrl.html` resulted in:

Error: Cannot find module './build/Release/vm_one.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\exokit\node_modules\vm-one\index.js:2:31)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)

---
![build_dir](https://user-images.githubusercontent.com/7916131/50990697-bbf2eb80-14e0-11e9-847b-94197d9109d8.JPG)

**Comment by Palmer-JC** [comment]
No quite sure where that is, but I made my own file from the console.  If not what you want let me know

---
[build log.txt](https://github.com/webmixedreality/exokit/files/2746818/build.log.txt)

**Comment by modulesio** [comment]
In that log I don't see the `vm-one`module being installed.

By chance did you have a build failure and then re-attempted an install again after installing windows build tools?

**Comment by Palmer-JC** [comment]
Well upped to exokit 0.506.

Install ran, still no such file, but it runs, or at least brings a window with the scene.  Now I can see what can be done.  Thanks.
