### ISSUE TITLE
Does Not Support sessionStorage [v0.0.206]

### ISSUE THREAD

**Issue by cmdrflexo** [webmixedreality/exokit#736]
Undefined `sessionStorage` error from `window.vm.run()`.

```
PS E:\exokit-master-v0.0.206> node . #
[x] window.location = "http://127.0.0.1:5500/index.html"
'http://127.0.0.1:5500/index.html'
[x] ReferenceError: sessionStorage is not defined
    at http://127.0.0.1:5500/index.html:51:4
    at http://127.0.0.1:5500/index.html:55:5
    at Object._runJavascript (E:\exokit-master-v0.0.206\src\utils.js:67:15)
    at Resource.ownerDocument.resources.addResource [as getCb] (E:\exokit-master-v0.0.206\src\DOM.js:1642:13)
    at Promise (E:\exokit-master-v0.0.206\src\core.js:93:12)
    at new Promise (<anonymous>)
    at Resource.get (E:\Projects\Exokit\exokit\exokit-master-v0.0.206\src\core.js:92:12)
    at Resources.drain (E:\exokit-master-v0.0.206\src\core.js:171:16)
    at Promise (E:\exokit-master-v0.0.206\src\core.js:164:12)
    at new Promise (<anonymous>)
```
`index.html` (VSCode/Live-Server):
```HTML
<!-- Code injected by live-server -->
<script type="text/javascript">
	// <![CDATA[  <-- For SVG support
	if ('WebSocket' in window) {
		(function () {
			function refreshCSS() {
				var sheets = [].slice.call(document.getElementsByTagName("link"));
				var head = document.getElementsByTagName("head")[0];
				for (var i = 0; i < sheets.length; ++i) {
					var elem = sheets[i];
					head.removeChild(elem);
					var rel = elem.rel;
					if (elem.href && typeof rel != "string" || rel.length == 0 || rel.toLowerCase() == "stylesheet") {
						var url = elem.href.replace(/(&|\?)_cacheOverride=\d+/, '');
						elem.href = url + (url.indexOf('?') >= 0 ? '&' : '?') + '_cacheOverride=' + (new Date().valueOf());
					}
					head.appendChild(elem);
				}
			}
			var protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://';
			var address = protocol + window.location.host + window.location.pathname + '/ws';
			var socket = new WebSocket(address);
			socket.onmessage = function (msg) {
				if (msg.data == 'reload') window.location.reload();
				else if (msg.data == 'refreshcss') refreshCSS();
			};
			if (sessionStorage && !sessionStorage.getItem('IsThisFirstTime_Log_From_LiveServer')) {
				console.log('Live reload enabled.');
				sessionStorage.setItem('IsThisFirstTime_Log_From_LiveServer', true);
			}
		})();
	}
	else {
		console.error('Upgrade your browser. This Browser is NOT supported WebSocket for Live-Reloading.');
	}
	// ]]>
</script>```

**Comment by modulesio** [comment]
`206`? I'm assuming `506`.

**Comment by cmdrflexo** [comment]
> `206`? I'm assuming `506`.

yes

**Comment by modulesio** [comment]
Should be in the latest release 👍.
