### ISSUE TITLE
Random crash.

### ISSUE THREAD

**Issue by ChrisEddy** [webmixedreality/exokit#76]
I was both in a party and using the voice option and the screen locked up and hard crashed with a "not-responding"
This is the error that the CLI spit out:

TypeError: mediaStream.getTracks is not a function
    at unsetMediaStream (js/xrmp-three.js:185:36)
    at Object3D.localPlayerMesh.unsetMediaStream (js/xrmp-three.js:193:9)
    at _closeMic (file:///C:/exokit/node_modules/exokit-home/index.html:269:28)
    at file:///C:/exokit/node_modules/exokit-home/index.html:1757:19
    at _updateIntersections (file:///C:/exokit/node_modules/exokit-home/index.html:1814:11)
    at animate (file:///C:/exokit/node_modules/exokit-home/index.html:1911:7)
    at _handleRaf (C:\exokit\core.js:3271:9)
    at tickAnimationFrame (C:\exokit\core.js:3298:9)
    at Timeout._recurse [as _onTimeout] (C:\exokit\index.js:957:12)
    at ontimeout (timers.js:427:11)

**Comment by modulesio** [comment]
Might be fixed when https://github.com/webmixedreality/exokit/releases/tag/v0.0.277 drops.

**Comment by modulesio** [comment]
Seems good in https://github.com/webmixedreality/exokit/releases/tag/v0.0.277.

I think it was just a matter of https://github.com/webmixedreality/exokit/releases/tag/v0.0.276 being WIP.

If this repros please re-open!
