### ISSUE TITLE
Sketchfab support 

### ISSUE THREAD

**Issue by chrislatorres** [webmixedreality/exokit#816]
[Sketchfab supports WebVR.](https://help.sketchfab.com/hc/en-us/articles/204777439-Desktop-WebVR-Vive-Oculus-?page=4&utm_campaign=vr_hints&utm_source=website#comments) Similar to #493. 

---------------------------------------

Command ran: ` node . -x webvr https://sketchfab.com/models/3e7fd0f34af540e4869b213510306b1f/embed`

----------------------------------------

```
$ node . -x webvr https://sketchfab.com/models/3e7fd0f34af540e4869b213510306b1f/embed
Failed to JSON decode DOM data.
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at y (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:151374)
    at Object.8 (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:342584)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at Object.212 (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:107439)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at Module.1154 (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:10423)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at c (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:387)
    at a (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:250)
    at https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:3499
    at https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:3519
    at Object._runJavascript (/home/chris/github/exokit/src/utils.js:71:15)
    at ownerDocument.defaultView.fetch.then.then.s (/home/chris/github/exokit/src/DOM.js:1655:17)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
Failed to JSON decode DOM data.
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at y (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:151374)
    at https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:237571
    at Object.39 (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:237656)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at Object.148 (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:36913)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at Object.212 (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:107579)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at Module.1154 (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:10423)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at c (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:387)
    at a (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:250)
    at https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:3499
    at https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:3519
    at Object._runJavascript (/home/chris/github/exokit/src/utils.js:71:15)
Failed to JSON decode DOM data.
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at y (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:151374)
    at Object.212 (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:107632)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at Module.1154 (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:10423)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at c (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:387)
    at a (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:250)
    at https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:3499
    at https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:3519
    at Object._runJavascript (/home/chris/github/exokit/src/utils.js:71:15)
    at ownerDocument.defaultView.fetch.then.then.s (/home/chris/github/exokit/src/DOM.js:1655:17)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
Sentry was not installed ; it is manually disabled.
Effect error: TypeError: Cannot read property 'isAnonymous' of undefined
    at effect (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:90504)
    at https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:77374
    at Object.dispatch (https://static.sketchfab.com/static/builds/web/dist/vendors-3590db61537cd704cdef.js:79:13254)
    at Function.me (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:307524)
    at t.a (https://static.sketchfab.com/static/builds/web/dist/viewer-9438fc2b8985e1d7d1c6.js:1:647753)
    at Object.34 (https://static.sketchfab.com/static/builds/web/dist/viewer-9438fc2b8985e1d7d1c6.js:1:947378)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at Object.123 (https://static.sketchfab.com/static/builds/web/dist/viewer-9438fc2b8985e1d7d1c6.js:1:260120)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at Object.169 (https://static.sketchfab.com/static/builds/web/dist/viewer-9438fc2b8985e1d7d1c6.js:1:312601)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at Object.382 (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:173701)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at Module.1154 (https://static.sketchfab.com/static/builds/web/dist/embed-c3931559d9da7a9a77be.js:1:10609)
    at n (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:519)
    at c (https://static.sketchfab.com/static/builds/web/dist/runtime-0499ff2b88077757922a.js:1:387)
couldn't load mixpanel
{ Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:431:23)
    at TLSSocket.emit (events.js:202:15)
    at TLSSocket.EventEmitter.emit (domain.js:446:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17) code: 'ECONNRESET' }
{ Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:431:23)
    at TLSSocket.emit (events.js:202:15)
    at TLSSocket.EventEmitter.emit (domain.js:446:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17) code: 'ECONNRESET' }
Bugsnag:  Encountered an uncaught error, terminating…
Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:431:23)
    at TLSSocket.emit (events.js:202:15)
    at TLSSocket.EventEmitter.emit (domain.js:446:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**Comment by modulesio** [comment]
Is there a way we can get cleaner source for this? i.e. is Sketchfab using a framework?

**Comment by modulesio** [comment]
This should be booting to grey gl scene with no errors now; for some reason the model load doesn’t complete.

Needs more investigation.

**Comment by chrislatorres** [comment]
Just tested
`node . -x webvr https://sketchfab.com/models/3e7fd0f34af540e4869b213510306b1f/embed` hangs 

------------------------------------------------- 

`node . -x webvr https://sketchfab.com/models/3e7fd0f34af540e4869b213510306b1f/`
 , got grey screen then:
```
{ Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:431:23)
    at TLSSocket.emit (events.js:202:15)
    at TLSSocket.EventEmitter.emit (domain.js:446:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17) code: 'ECONNRESET' }
{ Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:431:23)
    at TLSSocket.emit (events.js:202:15)
    at TLSSocket.EventEmitter.emit (domain.js:446:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17) code: 'ECONNRESET' }
{ Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:431:23)
    at TLSSocket.emit (events.js:202:15)
    at TLSSocket.EventEmitter.emit (domain.js:446:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17) code: 'ECONNRESET' }
{ Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:431:23)
    at TLSSocket.emit (events.js:202:15)
    at TLSSocket.EventEmitter.emit (domain.js:446:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17) code: 'ECONNRESET' }
Bugsnag:  Encountered an uncaught error, terminating…
Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at TLSSocket.socketOnEnd (_http_client.js:431:23)
    at TLSSocket.emit (events.js:202:15)
    at TLSSocket.EventEmitter.emit (domain.js:446:20)
    at endReadableNT (_stream_readable.js:1129:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
```

**Comment by modulesio** [comment]
Yeah, as far as I can tell the user code doesn't load up a model or initialize rendering.
