### ISSUE TITLE
Google Poly support

### ISSUE THREAD

**Issue by chrislatorres** [webmixedreality/exokit#822]
[Google Poly](https://poly.google.com/) supports webVR. 

--------------

Command ran: `node . -https://poly.google.com/view/6uUJxEHUKW0`

---------------

```
$ node . https://poly.google.com/view/6uUJxEHUKW0
TypeError: Cannot read property 'document' of null
    at new a (/_/scs/mss-static/_/js/k=boq-vr.VrZandriaUi.en_US.cG8NqNj_qC0.O/am=EAI/rt=j/d=1/excm=watchview,_b,_tp/ed=1/dg=0/rs=AGWRrUBjlUxYJTN6IADbJoQSC1jKUiNj4w/m=_b,_tp:95:307)
    at Aaa (/_/scs/mss-static/_/js/k=boq-vr.VrZandriaUi.en_US.cG8NqNj_qC0.O/am=EAI/rt=j/d=1/excm=watchview,_b,_tp/ed=1/dg=0/rs=AGWRrUBjlUxYJTN6IADbJoQSC1jKUiNj4w/m=_b,_tp:96:192)
    at Object._.Yc (/_/scs/mss-static/_/js/k=boq-vr.VrZandriaUi.en_US.cG8NqNj_qC0.O/am=EAI/rt=j/d=1/excm=watchview,_b,_tp/ed=1/dg=0/rs=AGWRrUBjlUxYJTN6IADbJoQSC1jKUiNj4w/m=_b,_tp:94:232)
    at ok.Gg (/_/scs/mss-static/_/js/k=boq-vr.VrZandriaUi.en_US.cG8NqNj_qC0.O/am=EAI/rt=j/d=1/excm=watchview,_b,_tp/ed=1/dg=0/rs=AGWRrUBjlUxYJTN6IADbJoQSC1jKUiNj4w/m=_b,_tp:246:77)
    at Um.Kg (/_/scs/mss-static/_/js/k=boq-vr.VrZandriaUi.en_US.cG8NqNj_qC0.O/am=EAI/rt=j/d=1/excm=watchview,_b,_tp/ed=1/dg=0/rs=AGWRrUBjlUxYJTN6IADbJoQSC1jKUiNj4w/m=_b,_tp:328:464)
    at wd (/_/scs/mss-static/_/js/k=boq-vr.VrZandriaUi.en_US.cG8NqNj_qC0.O/am=EAI/rt=j/d=1/excm=watchview,_b,_tp/ed=1/dg=0/rs=AGWRrUBjlUxYJTN6IADbJoQSC1jKUiNj4w/m=_b,_tp:103:39)
    at df (/_/scs/mss-static/_/js/k=boq-vr.VrZandriaUi.en_US.cG8NqNj_qC0.O/am=EAI/rt=j/d=1/excm=watchview,_b,_tp/ed=1/dg=0/rs=AGWRrUBjlUxYJTN6IADbJoQSC1jKUiNj4w/m=_b,_tp:142:37)
    at of._.f.du (/_/scs/mss-static/_/js/k=boq-vr.VrZandriaUi.en_US.cG8NqNj_qC0.O/am=EAI/rt=j/d=1/excm=watchview,_b,_tp/ed=1/dg=0/rs=AGWRrUBjlUxYJTN6IADbJoQSC1jKUiNj4w/m=_b,_tp:137:345)
    at /_/scs/mss-static/_/js/k=boq-vr.VrZandriaUi.en_US.cG8NqNj_qC0.O/am=EAI/rt=j/d=1/excm=watchview,_b,_tp/ed=1/dg=0/rs=AGWRrUBjlUxYJTN6IADbJoQSC1jKUiNj4w/m=_b,_tp:342:32
    at /_/scs/mss-static/_/js/k=boq-vr.VrZandriaUi.en_US.cG8NqNj_qC0.O/am=EAI/rt=j/d=1/excm=watchview,_b,_tp/ed=1/dg=0/rs=AGWRrUBjlUxYJTN6IADbJoQSC1jKUiNj4w/m=_b,_tp:349:4
```

**Comment by modulesio** [comment]
What is the requirement to trigger WebVR entry in Poly?

**Comment by chrislatorres** [comment]
Not able to test for desktop at the moment, but there is a button to enter VR on mobile:
![IMG_20190309_141551_290](https://user-images.githubusercontent.com/29695350/54076927-c75f5a80-4276-11e9-8d11-e14fe9f9efa7.jpg)

**Comment by modulesio** [comment]
Thanks, I mean technically speaking, what are the checks and entry architecture for Poly + the other examples? They are probably all different.

**Comment by chrislatorres** [comment]
Just tested. new error appended to the original:
```
failed to load image: https://lh3.googleusercontent.com/xBVJICXuOPUgbp8LtIxPuRpGq2_CMbHUqu-iGpR0-YpMXHPTUtHHeGLEdcBaYiUd
Error: img src got invalid status code (url: "https://lh3.googleusercontent.com/xBVJICXuOPUgbp8LtIxPuRpGq2_CMbHUqu-iGpR0-YpMXHPTUtHHeGLEdcBaYiUd", code: 500)
    at ownerDocument.defaultView.fetch.then.res (/home/chris/github/exokit/src/DOM.js:2483:39)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
ErrorEvent {
  type: 'error',
  target:
   <img src="https://lh3.googleusercontent.com/xBVJICXuOPUgbp8LtIxPuRpGq2_CMbHUqu-iGpR0-YpMXHPTUtHHeGLEdcBaYiUd" class="lBiGI-LwH6nd-HiaYvf"/>,
  bubbles: false,
  cancelable: false,
  defaultPrevented: false,
  propagationStopped: false,
  currentTarget:
   <img src="https://lh3.googleusercontent.com/xBVJICXuOPUgbp8LtIxPuRpGq2_CMbHUqu-iGpR0-YpMXHPTUtHHeGLEdcBaYiUd" class="lBiGI-LwH6nd-HiaYvf"/>,
  message:
   'img src got invalid status code (url: "https://lh3.googleusercontent.com/xBVJICXuOPUgbp8LtIxPuRpGq2_CMbHUqu-iGpR0-YpMXHPTUtHHeGLEdcBaYiUd", code: 500)',
  stack:
   'Error: img src got invalid status code (url: "https://lh3.googleusercontent.com/xBVJICXuOPUgbp8LtIxPuRpGq2_CMbHUqu-iGpR0-YpMXHPTUtHHeGLEdcBaYiUd", code: 500)\n    at ownerDocument.defaultView.fetch.then.res (/home/chris/github/exokit/src/DOM.js:2483:39)\n    at processTicksAndRejections (internal/process/next_tick.js:81:5)' }
```
